language: python
python:
  - "3.5"

env:
  - FLASK=1.0.2
  - FLASK=0.10.1
  
cache: pip

before_script: 
  - easy_install distribute
  - pip install -r requirements.txt

script: 
  - python -m unittest api/test_api.py