language: python
python:
  - "3.7"
  - "3.5"
  - "2.7"

env:
  - FLASK=1.0.2
  - FLASK=0.10.1
  
cache: pip

before_script: 
  - easy_install distribute
  - pip install -r requirements.txt

script: 
  - py.test test_ api.py