language: python
python:
  - "3.7"
  - "3.5"
  - "2.7"

cache: pip

before_script: 
  - easy_install distribute
  - pip install -r requirements.txt

install: 
  - pip install -r requirements.txt

scripts: 
  - py.test test_ api.py